# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    #这是gzip压缩
    compression:
        enabled: true
        mime-types: application/json,application/xml,application/javascript,text/css,text/html,text/xml,text/plain
    port: 8080
#    context-path: /ui

# mysql
spring:
    # 环境 dev|test|pro，在pom.xml里进行了配置，默认是 dev，在线上环境，可以这样执行 java -jar xxx.jar --spring.profiles.active=pro，这样来启动项目
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
        encoding:
          force: true
    # 指定静态资源的路径
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/static/,classpath:/views/,file:${spring.fileupload.upload_path}
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    kafka:
        consumer:
            enable-auto-commit: true  #指定消息被消费之后自动提交偏移量（即消息的编号，表示消费到了哪个位置，消费者每消费完一条消息就会向kafka服务器汇报自己消消费到的那个消息的编号，以便于下次继续消费）。
            group-id: myGroup
            auto-offset-reset: latest #从最近的地方开始消费
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-deserializer: org.apache.kafka.common.serialization.StringSerializer
            value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    thymeleaf:
        cache: false
        prefix: classpath:/views/
        suffix: .html
        encoding: UTF-8
    pushgateway:
        server: 127.0.0.1:9091

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

